### PR TITLE
Tumblr: close conversation HTML tags in the right order

### PR DESCRIPTION
**Pull request by thachhoang**

### CODE REVIEW

**Comment by parkr** [comment]
Hey @thachhoang! Is this a recent change or has it been wrong all along?

**Comment by thachhoang** [comment]
This has been around since 2013 at least.

https://github.com/jekyll/jekyll-import/blob/079287ae014126897f82778d0874f6f0b0d89a32/lib/jekyll-import/importers/tumblr.rb#L109

**Comment by parkr** [comment]
@thachhoang Ouch! Thanks for this.

**Comment by parkr** [comment]
LGTM.

**Comment by parkr** [comment]
@jekyllbot: merge

**Pull request merged**
