### PR TITLE
DrupalCommon: centralize defaults & use config for layouts dir

### PR DESCRIPTION
**Pull request by parkr**
@borfast, would you mind taking a 👀 at this? Addresses 2 of my comments. 😄 

/cc #235

### CODE REVIEW

**Comment by borfast** [comment]
Looks good.

One question: is there a reason not to allow customising the `_posts` and `_drafts` directories like `_layouts`?

**Comment by parkr** [comment]
Sweet, thanks!

> One question: is there a reason not to allow customising the `_posts` and `_drafts` directories like `_layouts`?

Yeah. "Posts" is a collection and follows the convention of `_#{collection_label}`. I suppose we could allow reconfiguration of the drafts location in theory, but it came about right when we started pushing for more Convention over Configuration.

too many knobs

**Comment by parkr** [comment]
LGTM.

**Comment by parkr** [comment]
@jekyllbot: merge

**Pull request merged**
