### PR TITLE
wordpressdotcom: add install additional gem note in docs

### PR DESCRIPTION
**Pull request by lioncorpo**
Fyi

### CODE REVIEW

**Review by mj559940 — APPROVED** [review]

**Comment by mj559940** [comment]
If you require more granular access to a repository owned by your user account, consider transferring the repository to an organization. For more information, see "Transferring a repository."

Owner access for a

**Review by Jcsenterprisesllc — APPROVED** [review]
jcsenterprisesllc.github.io

**Comment by parkr** [comment]
@jekyllbot: merge +docs

**Comment by parkr** [comment]
Thank you so much!

**Pull request merged**
