### PR TITLE
DotClear importer

### PR DESCRIPTION
**Pull request by rivsc**

### CODE REVIEW

**Comment by DirtyF** [comment]
Je suis français, ça aide 😄

**Comment by DirtyF** [comment]
OK, remaining Rubocop offenses are not related to this importer, we'll fix them in anothePR.

**Comment by rivsc** [comment]
> Je suis français, ça aide 😄

Oui j'ai vu ^^.

> OK, remaining Rubocop offenses are not related to this importer, we'll fix them in anothePR.

Ok, thanks.

**Comment by DirtyF** [comment]
@rivsc Released in https://github.com/jekyll/jekyll-import/releases/tag/v0.19.0

**Pull request merged**
