### PR TITLE
Add workflow to automate tagging and releasing gem

### PR DESCRIPTION
**Pull request by ashmaroli**
Trigger a release when changes to `lib/**/version.rb` is pushed to `master`.

### CODE REVIEW

**Review by parkr — APPROVED** [review]
Let's give it a shot! Please merge this and then merge my release PR. If there are any problems, feel free to fix as needed.

**Comment by ashmaroli** [comment]
@jekyllbot: merge +dev

**Comment by q464pp** [comment]
可以拉取合併嗎？謝謝

**Review by Bryan2357 — COMMENTED** [review]
Approve

**Pull request merged**
