### PR TITLE
Change data[author] to a string scalar

### PR DESCRIPTION
**Pull request by isotopp**
Using the minima template, data[author] is supposed to be a string scala, but the conversion turns it into a map of displayname, author_login and author_email. author_login and author_email are also stored as separate scalar attributes. The fix turns data[author] into a string scalar field of displayname, fixing the display of the author name in the minima template.

### CODE REVIEW

**Comment by parkr** [comment]
There was a push to migrate away from the scalar author field and to a hash. I wonder how feasible that is, for example if it’s not backwards compatible then GitHub Pages can’t upgrade.

**Comment by ashmaroli** [comment]
> if it’s not backwards compatible then GitHub Pages can’t upgrade

@parkr This plugin is not bundled with `github-pages`, but it is a *"blessed gem"* for Jekyll. Is that cause of your concern?

**Comment by parkr** [comment]
@ashmaroli I was more thinking about the minima gem!

**Comment by ashmaroli** [comment]
> I was more thinking about the minima gem!

I see.. But Minima doesn't care about `author` in a document's front matter or data hash, just the `author` in the config file..

**Review by parkr — APPROVED** [review]

**Comment by parkr** [comment]
@jekyllbot: merge +fix

**Pull request merged**
