### PR TITLE
fix RuboCop

### PR DESCRIPTION
**Pull request by midzer**
Follow up to https://github.com/jekyll/jekyll-import/pull/544

### CODE REVIEW

**Review by parkr — APPROVED** [review]

**Comment by parkr** [comment]
@jekyllbot: merge +dev

**Comment by ashmaroli** [comment]
Whoa! @midzer, a couple of changes made here are incorrect and not at all equivalent to previous code. Please review changes once more.

P.S. I'm intentionally refraining from pointing the incorrect changes out in order to encourage you to identify those by yourselves.

**Comment by midzer** [comment]
@ashmaroli Sorry, I don't know what you mean. Can you give me a hint whats wrong with the code?

**Comment by ashmaroli** [comment]
> Can you give me a hint...

@midzer I am assuming that you are new to Ruby and therefore I understand that it would be a lot easier for you if I told you exactly what is incorrect. But I will still refrain from giving you the correct solution so as to encourage active knowledge-seeking from your end.

The incorrect changes are in the following:

```ruby
options = { directory => opts.fetch("directory", "") }
```
```ruby
if fd.include?(".") || fd.include?("..")
```

Once you realise the solutions, please open a pull request.

P.S. The test coverage for this project is scarce. So CI passing isn't a guarantee enough.

**Comment by parkr** [comment]
Ah, good catch @ashmaroli. I haven't made a release so any changes can be fixed before then.

**Pull request merged**
